/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_etudiants;

import com.mysql.jdbc.Connection;
import java.security.NoSuchAlgorithmException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author b.dasilva
 */
public class Inscription extends javax.swing.JDialog {

    private InterfaceGraphique fenetre;

    /**
     * Creates new form Connexion
     */
    public Inscription(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //positionnement au milieu de la fenetre parente
        this.setLocationRelativeTo(parent);
        //modal==true signifie que l'on ne peut pas revenir 
        //sur la precedente fenêtre dans fermer connexion
        this.setModal(true);
        //on stocke dans this.fenetre la référence vers la fenetre parente
        this.fenetre = (InterfaceGraphique) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneBackground = new javax.swing.JDesktopPane();
        jLabelNom = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrenom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelPromotion = new javax.swing.JLabel();
        jLabelIdentifiant = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordFieldMDP = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldSortiePromo = new javax.swing.JTextField();
        jLabelConfMDP = new javax.swing.JLabel();
        jPasswordFieldConfMDP = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jTextFieldCP = new javax.swing.JTextField();
        jButtonTest = new javax.swing.JButton();
        jLabelVille = new javax.swing.JLabel();
        jTextFieldVille = new javax.swing.JTextField();
        jLabelMail = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jLabelMobile = new javax.swing.JLabel();
        jTextFieldMobile = new javax.swing.JTextField();
        jLabelTel = new javax.swing.JLabel();
        jTextFieldTel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAdresse = new javax.swing.JTextField();
        jLabelCP = new javax.swing.JLabel();
        jTextFieldEntreePromo = new javax.swing.JTextField();
        jTextFieldIdentifiant = new javax.swing.JTextField();
        jTextFieldSiteWeb = new javax.swing.JTextField();
        jLabelRole = new javax.swing.JLabel();
        jComboBoxRole = new javax.swing.JComboBox<>();

        setResizable(false);

        jDesktopPaneBackground.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNom.setText("Nom");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inscription");

        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Prénom");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Site web");

        jLabelPromotion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPromotion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPromotion.setText("Entrée promotion");

        jLabelIdentifiant.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIdentifiant.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIdentifiant.setText("Identifiant");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Mot de passe");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Sortie promotion");

        jLabelConfMDP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelConfMDP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelConfMDP.setText("Confirmer le mot de passe");

        jPasswordFieldConfMDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConfMDPActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Créer l'employé");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonTest.setText("Test");
        jButtonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestActionPerformed(evt);
            }
        });

        jLabelVille.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelVille.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVille.setText("Ville");

        jLabelMail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMail.setText("Mail");

        jLabelMobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMobile.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMobile.setText("Mobile Perso.");

        jTextFieldMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMobileActionPerformed(evt);
            }
        });

        jLabelTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTel.setText("Tel. Profesionnel");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Adresse");

        jLabelCP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCP.setText("Code Postal");

        jTextFieldEntreePromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEntreePromoActionPerformed(evt);
            }
        });

        jLabelRole.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRole.setText("Rôle");

        jComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employe ", "Responsable ", "Dirigeant" }));
        jComboBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRoleActionPerformed(evt);
            }
        });

        jDesktopPaneBackground.setLayer(jLabelNom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jTextFieldNom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jTextFieldPrenom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabelPromotion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabelIdentifiant, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jPasswordFieldMDP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jTextFieldSortiePromo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabelConfMDP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jPasswordFieldConfMDP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jTextFieldCP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jButtonTest, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabelVille, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jTextFieldVille, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabelMail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jTextFieldMail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabelMobile, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jTextFieldMobile, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabelTel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jTextFieldTel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jTextFieldAdresse, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabelCP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jTextFieldEntreePromo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jTextFieldIdentifiant, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jTextFieldSiteWeb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jLabelRole, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneBackground.setLayer(jComboBoxRole, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneBackgroundLayout = new javax.swing.GroupLayout(jDesktopPaneBackground);
        jDesktopPaneBackground.setLayout(jDesktopPaneBackgroundLayout);
        jDesktopPaneBackgroundLayout.setHorizontalGroup(
            jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPaneBackgroundLayout.createSequentialGroup()
                        .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPaneBackgroundLayout.createSequentialGroup()
                                .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelVille, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneBackgroundLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDesktopPaneBackgroundLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldVille)
                                            .addComponent(jTextFieldMobile)
                                            .addComponent(jPasswordFieldMDP)
                                            .addComponent(jTextFieldSortiePromo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jTextFieldSiteWeb))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelMail, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCP, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPromotion)
                                    .addComponent(jLabelConfMDP)))
                            .addGroup(jDesktopPaneBackgroundLayout.createSequentialGroup()
                                .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jDesktopPaneBackgroundLayout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneBackgroundLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPasswordFieldConfMDP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldEntreePromo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneBackgroundLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabelRole, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jButtonTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jDesktopPaneBackgroundLayout.setVerticalGroup(
            jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneBackgroundLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNom)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCP)
                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMail)
                    .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVille))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTel)
                    .addComponent(jTextFieldMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMobile))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelPromotion)
                    .addComponent(jTextFieldEntreePromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSiteWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSortiePromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdentifiant)
                    .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldMDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelConfMDP)
                    .addComponent(jPasswordFieldConfMDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jDesktopPaneBackgroundLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jDesktopPaneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRole)
                            .addComponent(jComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonTest)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneBackground)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEntreePromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEntreePromoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEntreePromoActionPerformed

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTextFieldNom.getText().length() == 0 || jTextFieldAdresse.getText().length() == 0
                || jTextFieldVille.getText().length() == 0 || jTextFieldMobile.getText().length() == 0
                || jTextFieldSortiePromo.getText().length() == 0 || jPasswordFieldMDP.getText().length() == 0
                || jTextFieldPrenom.getText().length() == 0 || jTextFieldCP.getText().length() == 0
                || jTextFieldMail.getText().length() == 0 || jTextFieldTel.getText().length() == 0
                || jTextFieldEntreePromo.getText().length() == 0 || jTextFieldIdentifiant.getText().length() == 0
                || jPasswordFieldConfMDP.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Erreur de saisie, tout les champs à part site web doivent être renseignés.");

            this.fenetre.deconnecte();
        } else {

            try {
                //interrogation de la BD pour savoir si l'identifiant/mot de passe est correct
                //instanciation de la classe Driver du paquetage jdbc de mysql
                Class.forName("com.mysql.jdbc.Driver");
                //Chaine de connexion (prise dans l'onglet services)
                String connexionUrl = "jdbc:mysql://localhost:3333/GSBPerso?user=GSBPerso&password=toto";

                //etablissement de la connexion
                Connection monInscription = (Connection) DriverManager.getConnection(connexionUrl);

                //requete
                Statement requete = monInscription.createStatement();
                String nom = jTextFieldNom.getText();
                String prenom = jTextFieldPrenom.getText();
                String adresse_rue = jTextFieldAdresse.getText();
                String adresse_cp = jTextFieldCP.getText();
                String adresse_ville = jTextFieldVille.getText();
                String tel_personnel = jTextFieldMobile.getText();
                String tel_professionnel = jTextFieldTel.getText();
                String mail = jTextFieldMail.getText();
                String site_web = jTextFieldSiteWeb.getText();
                String annee_entree_promo = jTextFieldEntreePromo.getText();
                String annee_sortie_promo = jTextFieldSortiePromo.getText();
                String identifiant = jTextFieldIdentifiant.getText();
                String mdp = jPasswordFieldMDP.getText();
                String conf_mdp = jPasswordFieldConfMDP.getText();
                Integer idrole = jComboBoxRole.getSelectedIndex()+1;
                
                String mailsql = "SELECT mail FROM utilisateurs WHERE mail = '" + mail + "'";
                ResultSet mailRetournee = requete.executeQuery(mailsql);

                if (!jPasswordFieldMDP.getText().equals(jPasswordFieldConfMDP.getText())) {
                    JOptionPane.showMessageDialog(rootPane, "Les deux mots de passes ne sont pas identiques");
                } else if (mailRetournee.next()) {
                    JOptionPane.showMessageDialog(rootPane, "Cette adresse mail existe déjà.");

                } else {
                    //application du cryptage md5 au mdp
                    // ici on appelle md5 membre static de la classe outils
                    mdp = Outils.md5(mdp);

                    String reqsql = "INSERT INTO `utilisateurs`(`id_role`, `nom`, `prenom`, "
                            + "`adresse_rue`, `adresse_cp`, `adresse_ville`, `tel_personnel`, `tel_professionnel`, `mail`, "
                            + "`site_web`, `annee_entree_promotion`, `annee_sortie_promotion`, `identifiant`, `mot_de_passe`) VALUES "
                            + "('" + idrole +"', '" + nom + "', '" + prenom + "', '" + adresse_rue + "', '" + adresse_cp + "', '" + adresse_ville + "', '"
                            + tel_personnel + "', '" + tel_professionnel + "', '" + mail + "', '" + site_web + "', '" + annee_entree_promo + "', '"
                            + annee_sortie_promo + "', '" + identifiant + "', '" + mdp + "')";

                    System.out.println(reqsql);
                    
                    Integer lignesRetournees = requete.executeUpdate(reqsql);
                    if (lignesRetournees == 1) {
                        JOptionPane.showMessageDialog(rootPane, "Inscription réussie");
                        this.setVisible(false);
                    }
                }

            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(rootPane, "Classe de connexion mysql non trouvee..." + ex.toString());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "SQL exception ... " + ex.toString());

            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(Inscription.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestActionPerformed
        jTextFieldNom.setText("RandomNom");
        jTextFieldPrenom.setText("RandomPrenom");
        jTextFieldAdresse.setText("9 chemin de la prade");
        jTextFieldCP.setText("66000");
        jTextFieldVille.setText("Perpignan");
        jTextFieldMail.setText("randomtest.lurcat@gmail.com");
        jTextFieldMobile.setText("0696587458");
        jTextFieldTel.setText("0925845632");
        jTextFieldSiteWeb.setText("sitetamere");
        jTextFieldEntreePromo.setText("2016");
        jTextFieldSortiePromo.setText("2017");
        jTextFieldIdentifiant.setText("Randomid");
        jPasswordFieldMDP.setText("Randommdp");
        jPasswordFieldConfMDP.setText("Randommdp");
    }//GEN-LAST:event_jButtonTestActionPerformed

    private void jTextFieldMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMobileActionPerformed

    private void jPasswordFieldConfMDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldConfMDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldConfMDPActionPerformed

    private void jComboBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Inscription dialog = new Inscription(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonTest;
    private javax.swing.JComboBox<String> jComboBoxRole;
    private javax.swing.JDesktopPane jDesktopPaneBackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCP;
    private javax.swing.JLabel jLabelConfMDP;
    private javax.swing.JLabel jLabelIdentifiant;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMobile;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPromotion;
    private javax.swing.JLabel jLabelRole;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JPasswordField jPasswordFieldConfMDP;
    private javax.swing.JPasswordField jPasswordFieldMDP;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldEntreePromo;
    private javax.swing.JTextField jTextFieldIdentifiant;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldMobile;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldSiteWeb;
    private javax.swing.JTextField jTextFieldSortiePromo;
    private javax.swing.JTextField jTextFieldTel;
    private javax.swing.JTextField jTextFieldVille;
    // End of variables declaration//GEN-END:variables
}
