/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_etudiants;

import javax.swing.JOptionPane;

/**
 *
 * @author nc
 */
public class InterfaceGraphique extends javax.swing.JFrame {

    /**
     * attribut qui indique si l'etudiant est connecté ou non
     */
    private boolean connecte;
    private Responsables infoEtudiant;

    /**
     * interface graphique
     */
    private Connexion fenConnexion;
    private Deconnexion fenDeconnexion;
    private Inscription fenInscription;
    private InterfaceGraphique fenEmployes;
    private InterfaceGraphique fenResponsables;
    private InterfaceGraphique fenDirigeants;
    private GererInfosPersos fenGererInfosPersos;
    private GererFormations fenGererFormations;

    /**
     * constructeur : Creates new form InterfaceGraphique
     *
     */
    public InterfaceGraphique() {
        initComponents();
        //par defaut, la connexion est inactive
        this.connecte = false;
        //element du menu de deconnexion grisé
        this.majConnexion();
        //centrage
        this.setLocationRelativeTo(null);
        //titre 
        this.setTitle("Gestion des étudiants du bts sio");
        this.jDesktopPaneDirigeant.setVisible(false);
        this.jDesktopPaneResponsable.setVisible(false);
        this.jDesktopPaneEmploye.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneAccueil = new javax.swing.JDesktopPane();
        jButtonConnexion = new javax.swing.JButton();
        jDesktopPaneEmploye = new javax.swing.JDesktopPane();
        jButtonGenererCV = new javax.swing.JButton();
        jDesktopPaneDirigeant = new javax.swing.JDesktopPane();
        jButtonInscription = new javax.swing.JButton();
        jButtonGererRoles = new javax.swing.JButton();
        jButtonGenererCV2 = new javax.swing.JButton();
        jDesktopPaneResponsable = new javax.swing.JDesktopPane();
        jButtonGererPositions = new javax.swing.JButton();
        jButtonGenererCV1 = new javax.swing.JButton();
        nomMenuBar = new javax.swing.JMenuBar();
        fileMenuLogiciel = new javax.swing.JMenu();
        connexionMenuItem = new javax.swing.JMenuItem();
        deconnexionMenuItem = new javax.swing.JMenuItem();
        SortieMenuItem = new javax.swing.JMenuItem();
        jMenuGerer = new javax.swing.JMenu();
        jMenuItemInfosPersos = new javax.swing.JMenuItem();
        jMenuItemFormations = new javax.swing.JMenuItem();
        nomjMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jDesktopPaneAccueil.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPaneAccueil.setBorder(new javax.swing.border.MatteBorder(null));

        jButtonConnexion.setText("Se connecter");
        jButtonConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnexionActionPerformed(evt);
            }
        });

        jDesktopPaneAccueil.setLayer(jButtonConnexion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jDesktopPaneAccueilLayout = new org.jdesktop.layout.GroupLayout(jDesktopPaneAccueil);
        jDesktopPaneAccueil.setLayout(jDesktopPaneAccueilLayout);
        jDesktopPaneAccueilLayout.setHorizontalGroup(
            jDesktopPaneAccueilLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneAccueilLayout.createSequentialGroup()
                .add(128, 128, 128)
                .add(jButtonConnexion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jDesktopPaneAccueilLayout.setVerticalGroup(
            jDesktopPaneAccueilLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneAccueilLayout.createSequentialGroup()
                .add(129, 129, 129)
                .add(jButtonConnexion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jDesktopPaneEmploye.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPaneEmploye.setBorder(new javax.swing.border.MatteBorder(null));

        jButtonGenererCV.setText("Generer un CV");
        jButtonGenererCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenererCVActionPerformed(evt);
            }
        });

        jDesktopPaneEmploye.setLayer(jButtonGenererCV, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jDesktopPaneEmployeLayout = new org.jdesktop.layout.GroupLayout(jDesktopPaneEmploye);
        jDesktopPaneEmploye.setLayout(jDesktopPaneEmployeLayout);
        jDesktopPaneEmployeLayout.setHorizontalGroup(
            jDesktopPaneEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneEmployeLayout.createSequentialGroup()
                .add(68, 68, 68)
                .add(jButtonGenererCV, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jDesktopPaneEmployeLayout.setVerticalGroup(
            jDesktopPaneEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneEmployeLayout.createSequentialGroup()
                .add(74, 74, 74)
                .add(jButtonGenererCV, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jDesktopPaneDirigeant.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPaneDirigeant.setBorder(new javax.swing.border.MatteBorder(null));

        jButtonInscription.setText("Créer un employé");
        jButtonInscription.setAlignmentY(0.0F);
        jButtonInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscriptionActionPerformed(evt);
            }
        });

        jButtonGererRoles.setText("Gérer les rôles");
        jButtonGererRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGererRolesActionPerformed(evt);
            }
        });

        jButtonGenererCV2.setText("Générer un CV");
        jButtonGenererCV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenererCV2ActionPerformed(evt);
            }
        });

        jDesktopPaneDirigeant.setLayer(jButtonInscription, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneDirigeant.setLayer(jButtonGererRoles, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneDirigeant.setLayer(jButtonGenererCV2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jDesktopPaneDirigeantLayout = new org.jdesktop.layout.GroupLayout(jDesktopPaneDirigeant);
        jDesktopPaneDirigeant.setLayout(jDesktopPaneDirigeantLayout);
        jDesktopPaneDirigeantLayout.setHorizontalGroup(
            jDesktopPaneDirigeantLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneDirigeantLayout.createSequentialGroup()
                .add(129, 129, 129)
                .add(jDesktopPaneDirigeantLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButtonGenererCV2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jDesktopPaneDirigeantLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jButtonGererRoles, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButtonInscription, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jDesktopPaneDirigeantLayout.setVerticalGroup(
            jDesktopPaneDirigeantLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneDirigeantLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonGenererCV2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonInscription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonGererRoles, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25))
        );

        jDesktopPaneResponsable.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPaneResponsable.setBorder(new javax.swing.border.MatteBorder(null));

        jButtonGererPositions.setText("Gérer les positions");
        jButtonGererPositions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGererPositionsActionPerformed(evt);
            }
        });

        jButtonGenererCV1.setText("Générer un CV");
        jButtonGenererCV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenererCV1ActionPerformed(evt);
            }
        });

        jDesktopPaneResponsable.setLayer(jButtonGererPositions, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneResponsable.setLayer(jButtonGenererCV1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jDesktopPaneResponsableLayout = new org.jdesktop.layout.GroupLayout(jDesktopPaneResponsable);
        jDesktopPaneResponsable.setLayout(jDesktopPaneResponsableLayout);
        jDesktopPaneResponsableLayout.setHorizontalGroup(
            jDesktopPaneResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneResponsableLayout.createSequentialGroup()
                .add(127, 127, 127)
                .add(jDesktopPaneResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButtonGenererCV1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonGererPositions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jDesktopPaneResponsableLayout.setVerticalGroup(
            jDesktopPaneResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPaneResponsableLayout.createSequentialGroup()
                .add(50, 50, 50)
                .add(jButtonGererPositions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonGenererCV1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        fileMenuLogiciel.setMnemonic('f');
        fileMenuLogiciel.setText("Logiciel");

        connexionMenuItem.setMnemonic('o');
        connexionMenuItem.setText("Connexion");
        connexionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionMenuItemActionPerformed(evt);
            }
        });
        fileMenuLogiciel.add(connexionMenuItem);

        deconnexionMenuItem.setMnemonic('s');
        deconnexionMenuItem.setText("Déconnexion");
        deconnexionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexionMenuItemActionPerformed(evt);
            }
        });
        fileMenuLogiciel.add(deconnexionMenuItem);

        SortieMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SortieMenuItem.setMnemonic('x');
        SortieMenuItem.setText("Sortie");
        SortieMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortieMenuItemActionPerformed(evt);
            }
        });
        fileMenuLogiciel.add(SortieMenuItem);

        nomMenuBar.add(fileMenuLogiciel);

        jMenuGerer.setText("Gérer");

        jMenuItemInfosPersos.setText("Infos personnelles");
        jMenuItemInfosPersos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInfosPersosActionPerformed(evt);
            }
        });
        jMenuGerer.add(jMenuItemInfosPersos);

        jMenuItemFormations.setText("Formations");
        jMenuItemFormations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormationsActionPerformed(evt);
            }
        });
        jMenuGerer.add(jMenuItemFormations);

        nomMenuBar.add(jMenuGerer);
        nomMenuBar.add(nomjMenu);

        setJMenuBar(nomMenuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jDesktopPaneAccueil)
                .addContainerGap())
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(jDesktopPaneDirigeant)
                    .addContainerGap()))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(jDesktopPaneResponsable)
                    .add(20, 20, 20)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(11, 11, 11)
                    .add(jDesktopPaneEmploye)
                    .add(11, 11, 11)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jDesktopPaneAccueil, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(jDesktopPaneDirigeant, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(114, Short.MAX_VALUE)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(jDesktopPaneResponsable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(108, Short.MAX_VALUE)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(59, 59, 59)
                    .add(jDesktopPaneEmploye, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SortieMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortieMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SortieMenuItemActionPerformed

    private void connexionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionMenuItemActionPerformed
        /**
         * création de la fenetre de connexion et attachement de cette dernière
         * à l'interface maj de connecte en retour
         */
        this.fenConnexion = new Connexion(this, true);
        this.fenConnexion.setVisible(true);
    }//GEN-LAST:event_connexionMenuItemActionPerformed

    private void deconnexionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionMenuItemActionPerformed
        // TODO add your handling code here:
        fenDeconnexion = new Deconnexion(this, true);
        this.fenDeconnexion.setVisible(true);
    }//GEN-LAST:event_deconnexionMenuItemActionPerformed

    private void jButtonConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnexionActionPerformed
        this.fenConnexion = new Connexion(this, true);
        this.fenConnexion.setVisible(true);
    }//GEN-LAST:event_jButtonConnexionActionPerformed

    private void jButtonInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscriptionActionPerformed
        fenInscription = new Inscription(this, true);
        this.fenInscription.setVisible(true);
    }//GEN-LAST:event_jButtonInscriptionActionPerformed

    private void jButtonGererRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGererRolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGererRolesActionPerformed

    private void jMenuItemInfosPersosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInfosPersosActionPerformed
        fenGererInfosPersos = new GererInfosPersos(this, true);        
        this.fenGererInfosPersos.setVisible(true);
    }//GEN-LAST:event_jMenuItemInfosPersosActionPerformed

    private void jButtonGererPositionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGererPositionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGererPositionsActionPerformed

    private void jButtonGenererCV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenererCV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGenererCV1ActionPerformed

    private void jButtonGenererCV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenererCV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGenererCV2ActionPerformed

    private void jButtonGenererCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenererCVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGenererCVActionPerformed

    private void jMenuItemFormationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormationsActionPerformed
        fenGererFormations = new GererFormations(this, true);        
        this.fenGererFormations.setVisible(true);
    }//GEN-LAST:event_jMenuItemFormationsActionPerformed
    
    public void connecte(String leNom) {
        //maj de l'etat de la connexion
        this.connecte = true;
        //ajout du nom dans la fenetre
        this.nomjMenu.setText("Connecté en tant que : " + leNom);
        this.nomjMenu.setEnabled(false);
    }
    
    public void deconnecte() {
        this.connecte = false;
        this.nomjMenu.setText(null);
    }
    
    public void majConnexion() {
        deconnexionMenuItem.setEnabled(this.connecte);
        connexionMenuItem.setEnabled(!this.connecte);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGraphique().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SortieMenuItem;
    private javax.swing.JMenuItem connexionMenuItem;
    private javax.swing.JMenuItem deconnexionMenuItem;
    private javax.swing.JMenu fileMenuLogiciel;
    private javax.swing.JButton jButtonConnexion;
    private javax.swing.JButton jButtonGenererCV;
    private javax.swing.JButton jButtonGenererCV1;
    private javax.swing.JButton jButtonGenererCV2;
    private javax.swing.JButton jButtonGererPositions;
    private javax.swing.JButton jButtonGererRoles;
    private javax.swing.JButton jButtonInscription;
    private javax.swing.JDesktopPane jDesktopPaneAccueil;
    private javax.swing.JDesktopPane jDesktopPaneDirigeant;
    private javax.swing.JDesktopPane jDesktopPaneEmploye;
    private javax.swing.JDesktopPane jDesktopPaneResponsable;
    private javax.swing.JMenu jMenuGerer;
    private javax.swing.JMenuItem jMenuItemFormations;
    private javax.swing.JMenuItem jMenuItemInfosPersos;
    private javax.swing.JMenuBar nomMenuBar;
    private javax.swing.JMenu nomjMenu;
    // End of variables declaration//GEN-END:variables
}
